import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-center pt-6 pb-4">Omnii</h1>
        {children}
      </body>
    </html>
  )
}
